### ISSUE TITLE
Does this gem work?

### ISSUE THREAD

**Issue by lacostenycoder** [zywy/athena_health#2]
There are no instructions in the readme.   Not sure how to use this.
Any help is greatly appreciated.  Thanks!

**Comment by zywy** [comment]
There are snippets in the wiki https://github.com/zywy/athena_health/wiki/Initializing-new-client
Let me know if you need any help.

**Comment by lacostenycoder** [comment]
Yes, I figured out this part already.  It looks like not all the endpoints are set up?  Are you able to upload documents?  I'm looking to use this endpoint but have only been successful using curl.

`POST /patients/{patientid}/documents /preview1/:practiceid/patients/:patientid/documents`

**Comment by zywy** [comment]
The endpoint you mentioned is not supported in the gem yet. We've been continuously adding more and more endpoints but there's still a lot of them missing. Let me see if we have bandwidth to add ```/:patientid/documents``` immediately. Nevertheless, we do accept pull requests :)

**Comment by MatUrbanski** [comment]
@lacostenycoder I've added ```create_patient_document``` method. You can find information about it here:

https://github.com/zywy/athena_health/wiki/Create-patient-document

**Comment by lacostenycoder** [comment]
@MatUrbanski Thank you!  Is there a reason for the underscore in the `practice_id: 195_900` ?

**Comment by MatUrbanski** [comment]
The only one reason is better readability :)

**Comment by SpencerCDixon** [comment]
I've just been looking at source to learn how to use the gem.  Great work guys it looks fantastic!!  When I find some time I'll write up some documentation for the README so new users can get up and running quicker

**Comment by jordanleahy** [comment]
Hey Spencer!  We should connect sometime.  I'm in NYC but my partner is in Boston.  You ever in NYC?

We are a Dev shop working on a couple health tech related mobile applications.

**Comment by SpencerCDixon** [comment]
Sounds cool!  Unfortunately I'm never in NYC, but if you're ever in Boston feel free to reach out.  Email is: sdixon@athenahealth.com
