### ISSUE TITLE
NoMethodError find_patient

### ISSUE THREAD

**Issue by lacostenycoder** [zywy/athena_health#3]
I changed the practice idea displayed below to use generic default instead of our assigned sandbox number, but this was the error I got.  `pa.member_id`  in this example is getting the ID from a patient model in our rails app.

```
[59] pry(main)> p = client.find_patient(practice_id: 1959000, patient_id: pa.member_id)
ETHON: performed EASY effective_url=https://api.athenahealth.com/preview1/1959000/patients/26 response_code=200 return_code=ok total_time=0.752934
NoMethodError: undefined method `defaultpharmacyncpdpid=' for #<AthenaHealth::Patient:0x007fa554255110>
```

**Comment by MatUrbanski** [comment]
Hey, this issue is fixed in ```1.0.8``` version. Please update your gem version and everything should work fine.
